# Generated by Django 3.0.1 on 2020-01-20 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admintia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalletransaccion',
            name='CodigoProducto',
        ),
    ]
